# Alacritty terminal configuration for v0.13.2+ on GNU/Linux.

# working_directory = none

[colors.normal]
black   = "#373b41"
blue    = "#6699cc"
cyan    = "#66cccc"
green   = "#99cc99"
magenta = "#cc99cc"
red     = "#f2777a"
white   = "#ffffff"
yellow  = "#ffcc66"

[font]
size    = 14.0

[font.bold]
family  = "Source Code Pro Medium"

[font.normal]
family  = "Source Code Pro"

[mouse]
hide_when_typing = true

[shell]
program = "/bin/bash"
args    = ["-l", "-c", "tmux attach || tmux"]

[window]
decorations = "none"

[[keyboard.bindings]]
action  = "Copy"
key     = "C"
mods    = "Alt"

[[keyboard.bindings]]
action  = "Paste"
key     = "V"
mods    = "Alt"

# vim: ft=toml
