#! perl
# Filename: fullscreen
# Info: Toggle/Switching Full-screen on rxvt-unicode.
# - https://bbs.archlinux.org/viewtopic.php?pid=1155345#p1155345

sub on_user_command {
    my ($self, $cmd) = @_;
	#open (MYFILE, '>/dev/shm/urlog.log');
    #print MYFILE "Called\n";
    if ($cmd eq "fullscreen:switch") {
		#print MYFILE "I'm in1!!!!!\n";
        my $dummy = `wmctrl -r :ACTIVE: -b toggle,fullscreen,above` ;
    }
    close (MYFILE);
}

